spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.vatoalfojbqvbvqjxdcx
    password: "DAb1239df0#!sd"
    driver-class-name: org.postgresql.Driver



logging:
  level:
    org.unimelb: debug
    com.baomidou.mybatisplus: debug
    org.apache.ibatis: debug
